import pandas as pd
import numpy as np
import random

# Set random seed for reproducibility
np.random.seed(42)
random.seed(42)

# Define the number of songs per mood
n_songs_per_mood = 50

# Dictionary to store songs by mood with accurate details
songs_by_mood = {
    'Happy': [
        {'name': 'Kala Chashma', 'artist': 'Badshah, Neha Kakkar', 'year': 2016, 'popularity': 95},
        {'name': 'Balam Pichkari', 'artist': 'Vishal Dadlani, Shalmali Kholgade', 'year': 2013, 'popularity': 92},
        {'name': 'Naatu Naatu', 'artist': 'Rahul Sipligunj, Kaala Bhairava', 'year': 2022, 'popularity': 98},
        {'name': 'Bijlee Bijlee', 'artist': 'Harrdy Sandhu', 'year': 2021, 'popularity': 90},
        {'name': 'Arabic Kuthu', 'artist': 'Anirudh Ravichander, Jonita Gandhi', 'year': 2022, 'popularity': 93},
        {'name': 'Param Sundari', 'artist': 'A.R. Rahman, Shreya Ghoshal', 'year': 2021, 'popularity': 89},
        {'name': 'Ghungroo', 'artist': 'Arijit Singh, Shilpa Rao', 'year': 2019, 'popularity': 91},
        {'name': 'Kamariya', 'artist': 'Aastha Gill, Divya Kumar', 'year': 2018, 'popularity': 88},
        {'name': 'Kar Gayi Chull', 'artist': 'Badshah, Fazilpuria', 'year': 2016, 'popularity': 89},
        {'name': 'Swag Se Swagat', 'artist': 'Vishal Dadlani, Neha Bhasin', 'year': 2017, 'popularity': 92},
        {'name': 'Dance Ka Bhoot', 'artist': 'Arijit Singh', 'year': 2022, 'popularity': 87},
        {'name': 'Jhoome Jo Pathaan', 'artist': 'Arijit Singh, Sukriti Kakar', 'year': 2023, 'popularity': 94},
        {'name': 'What Jhumka?', 'artist': 'Arijit Singh, Jonita Gandhi', 'year': 2023, 'popularity': 93},
        {'name': 'Kudiyee Ni Teri', 'artist': 'Vishal Mishra, Zahrah S Khan', 'year': 2023, 'popularity': 85},
        {'name': 'Morni Banke', 'artist': 'Guru Randhawa, Neha Kakkar', 'year': 2018, 'popularity': 87},
        {'name': 'Badtameez Dil', 'artist': 'Benny Dayal', 'year': 2013, 'popularity': 89},
        {'name': 'Gallan Goodiyaan', 'artist': 'Yashita Sharma, Manish J. Tipu', 'year': 2015, 'popularity': 88},
        {'name': 'London Thumakda', 'artist': 'Labh Janjua, Sonu Kakkar', 'year': 2014, 'popularity': 87},
        {'name': 'Proper Patola', 'artist': 'Diljit Dosanjh, Badshah', 'year': 2018, 'popularity': 86},
        {'name': 'Chittiyaan Kalaiyaan', 'artist': 'Meet Bros, Kanika Kapoor', 'year': 2015, 'popularity': 85},
        {'name': 'Brown Rang', 'artist': 'Yo Yo Honey Singh', 'year': 2012, 'popularity': 86},
        {'name': 'Amplifier', 'artist': 'Imran Khan', 'year': 2009, 'popularity': 84},
        {'name': 'Halamithi Habibo', 'artist': 'Anirudh Ravichander', 'year': 2022, 'popularity': 91},
        {'name': 'Manohari', 'artist': 'Mohana Bhogaraju, Revanth', 'year': 2015, 'popularity': 87},
        {'name': 'Naacho Naacho', 'artist': 'Vishal Mishra, Rahul Sipligunj', 'year': 2021, 'popularity': 92},
        {'name': 'Besharam Rang', 'artist': 'Shilpa Rao, Caralisa Monteiro', 'year': 2022, 'popularity': 90},
        {'name': 'Saami Saami', 'artist': 'Mounika Yadav', 'year': 2021, 'popularity': 89},
        {'name': 'Srivalli', 'artist': 'Sid Sriram', 'year': 2021, 'popularity': 90},
        {'name': 'Oo Antava', 'artist': 'Indravathi Chauhan', 'year': 2021, 'popularity': 94},
        {'name': 'Thumkeshwari', 'artist': 'Sachin-Jigar, Rashmeet Kaur', 'year': 2022, 'popularity': 86},
        {'name': 'Kaavaalaa', 'artist': 'Anirudh Ravichander, Shilpa Rao', 'year': 2023, 'popularity': 95},
        {'name': 'Current Laga Re', 'artist': 'Nakash Aziz, Dhvani Bhanushali', 'year': 2022, 'popularity': 89},
        {'name': 'Koka', 'artist': 'Badshah, Jasbir Jassi', 'year': 2019, 'popularity': 85},
        {'name': 'Chamak Challo', 'artist': 'Akon, Hamsika Iyer', 'year': 2011, 'popularity': 88},
        {'name': 'Genda Phool', 'artist': 'Badshah, Payal Dev', 'year': 2020, 'popularity': 87},
        {'name': 'Hookah Bar', 'artist': 'Himesh Reshammiya', 'year': 2012, 'popularity': 83},
        {'name': 'Pasoori Nu', 'artist': 'Arijit Singh, Tulsi Kumar', 'year': 2023, 'popularity': 94},
        {'name': 'Kusu Kusu', 'artist': 'Zahrah S Khan, Dev Negi', 'year': 2021, 'popularity': 86},
        {'name': 'The Punjaabban Song', 'artist': 'Gippy Grewal, Zahrah S Khan', 'year': 2022, 'popularity': 87},
        {'name': 'Tumhe Jo Maine Dekha', 'artist': 'Abhijeet Bhattacharya', 'year': 2004, 'popularity': 84},
        {'name': 'Laung Laachi', 'artist': 'Mannat Noor', 'year': 2018, 'popularity': 88},
        {'name': 'Dil Chori', 'artist': 'Yo Yo Honey Singh', 'year': 2017, 'popularity': 86},
        {'name': 'Aankh Marey', 'artist': 'Neha Kakkar, Mika Singh', 'year': 2018, 'popularity': 90},
        {'name': 'High Rated Gabru', 'artist': 'Guru Randhawa', 'year': 2017, 'popularity': 87},
        {'name': 'Mercy', 'artist': 'Badshah', 'year': 2017, 'popularity': 85},
        {'name': 'Suit Suit', 'artist': 'Guru Randhawa, Arjun', 'year': 2017, 'popularity': 86},
        {'name': 'Chogada', 'artist': 'Darshan Raval, Asees Kaur', 'year': 2018, 'popularity': 88},
        {'name': 'Sheila Ki Jawani', 'artist': 'Sunidhi Chauhan', 'year': 2010, 'popularity': 89},
        {'name': 'Fevicol Se', 'artist': 'Mamta Sharma', 'year': 2012, 'popularity': 87},
        {'name': 'Malhari', 'artist': 'Vishal Dadlani', 'year': 2015, 'popularity': 88}
    ],
    'Sad': [
        {'name': 'Channa Mereya', 'artist': 'Arijit Singh', 'year': 2016, 'popularity': 95},
        {'name': 'Tum Hi Ho', 'artist': 'Arijit Singh', 'year': 2013, 'popularity': 96},
        {'name': 'Agar Tum Saath Ho', 'artist': 'Arijit Singh, Alka Yagnik', 'year': 2015, 'popularity': 94},
        {'name': 'Pehli Dafa', 'artist': 'Atif Aslam', 'year': 2017, 'popularity': 88},
        {'name': 'Raataan Lambiyan', 'artist': 'Jubin Nautiyal, Asees Kaur', 'year': 2021, 'popularity': 92},
        {'name': 'Laal Ishq', 'artist': 'Arijit Singh', 'year': 2013, 'popularity': 87},
        {'name': 'Kalank Title Track', 'artist': 'Arijit Singh', 'year': 2019, 'popularity': 89},
        {'name': 'Shayad', 'artist': 'Arijit Singh', 'year': 2020, 'popularity': 91},
        {'name': 'Thodi Jagah', 'artist': 'Arijit Singh', 'year': 2019, 'popularity': 88},
        {'name': 'Dil Na Jaaneya', 'artist': 'Rochak Kohli, Lauv', 'year': 2019, 'popularity': 85},
        {'name': 'Khairiyat', 'artist': 'Arijit Singh', 'year': 2019, 'popularity': 90},
        {'name': 'Bekhayali', 'artist': 'Sachet Tandon', 'year': 2019, 'popularity': 93},
        {'name': 'Ae Dil Hai Mushkil', 'artist': 'Arijit Singh', 'year': 2016, 'popularity': 92},
        {'name': 'Taaron Ke Shehar', 'artist': 'Neha Kakkar, Jubin Nautiyal', 'year': 2020, 'popularity': 89},
        {'name': 'Tujhe Kitna Chahne Lage', 'artist': 'Arijit Singh', 'year': 2019, 'popularity': 91},
        {'name': 'Kaise Hua', 'artist': 'Vishal Mishra', 'year': 2019, 'popularity': 87},
        {'name': 'Phir Mulaaqat', 'artist': 'Jubin Nautiyal', 'year': 2019, 'popularity': 86},
        {'name': 'Lut Gaye', 'artist': 'Jubin Nautiyal', 'year': 2021, 'popularity': 93},
        {'name': 'Mann Bharryaa 2.0', 'artist': 'B Praak', 'year': 2021, 'popularity': 90},
        {'name': 'Dil Ibaadat', 'artist': 'KK', 'year': 2009, 'popularity': 86},
        {'name': 'Mehram', 'artist': 'Sachet Tandon', 'year': 2020, 'popularity': 87},
        {'name': 'Chhod Denge', 'artist': 'Parampara Tandon', 'year': 2021, 'popularity': 85},
        {'name': 'Mera Pyaar Tera Pyaar', 'artist': 'Arijit Singh', 'year': 2018, 'popularity': 84},
        {'name': 'Phir Le Aya Dil', 'artist': 'Arijit Singh', 'year': 2012, 'popularity': 88},
        {'name': 'Tera Ban Jaunga', 'artist': 'Akhil Sachdeva, Tulsi Kumar', 'year': 2019, 'popularity': 89},
        {'name': 'Judaiyaan', 'artist': 'Darshan Raval, Shreya Ghoshal', 'year': 2020, 'popularity': 87},
        {'name': 'Dil Tod Ke', 'artist': 'B Praak', 'year': 2020, 'popularity': 88},
        {'name': 'Rozana', 'artist': 'Shreya Ghoshal', 'year': 2017, 'popularity': 86},
        {'name': 'Hawayein', 'artist': 'Arijit Singh', 'year': 2017, 'popularity': 92},
        {'name': 'Soch Na Sake', 'artist': 'Arijit Singh, Tulsi Kumar', 'year': 2015, 'popularity': 88},
        {'name': 'Khamoshiyan', 'artist': 'Arijit Singh', 'year': 2015, 'popularity': 87},
        {'name': 'Hasi', 'artist': 'Ami Mishra', 'year': 2015, 'popularity': 85},
        {'name': 'Kabira', 'artist': 'Tochi Raina, Rekha Bhardwaj', 'year': 2013, 'popularity': 89},
        {'name': 'Tu Hi Yaar Mera', 'artist': 'Arijit Singh, Neha Kakkar', 'year': 2019, 'popularity': 86},
        {'name': 'Jeena Jeena', 'artist': 'Atif Aslam', 'year': 2015, 'popularity': 87},
        {'name': 'Tujhe Kitna Chahein Aur', 'artist': 'Jubin Nautiyal', 'year': 2019, 'popularity': 88},
        {'name': 'Jinke Liye', 'artist': 'Neha Kakkar', 'year': 2020, 'popularity': 84},
        {'name': 'Baarish', 'artist': 'Ash King, Shashaa Tirupati', 'year': 2017, 'popularity': 87},
        {'name': 'Main Jis Din Bhulaa Du', 'artist': 'Jubin Nautiyal, Tulsi Kumar', 'year': 2021, 'popularity': 89},
        {'name': 'Filhaal', 'artist': 'B Praak', 'year': 2019, 'popularity': 92},
        {'name': 'Filhaal 2 Mohabbat', 'artist': 'B Praak', 'year': 2021, 'popularity': 91},
        {'name': 'Mere Sohneya', 'artist': 'Sachet Tandon, Parampara Thakur', 'year': 2019, 'popularity': 90},
        {'name': 'Enna Sona', 'artist': 'Arijit Singh', 'year': 2017, 'popularity': 88},
        {'name': 'Humsafar', 'artist': 'Akhil Sachdeva', 'year': 2017, 'popularity': 87},
        {'name': 'Mast Magan', 'artist': 'Arijit Singh, Chinmayi', 'year': 2014, 'popularity': 86},
        {'name': 'Thoda Thoda Pyaar', 'artist': 'Stebin Ben', 'year': 2021, 'popularity': 89},
        {'name': 'Bhula Dunga', 'artist': 'Darshan Raval', 'year': 2020, 'popularity': 85},
        {'name': 'Wafa Na Raas Aayee', 'artist': 'Jubin Nautiyal', 'year': 2021, 'popularity': 87},
        {'name': 'Hamari Adhuri Kahani', 'artist': 'Arijit Singh', 'year': 2015, 'popularity': 88},
        {'name': 'Pachtaoge', 'artist': 'Arijit Singh', 'year': 2019, 'popularity': 90}
    ],
    'Calm': [
        {'name': 'Tum Se Hi', 'artist': 'Mohit Chauhan', 'year': 2007, 'popularity': 92},
        {'name': 'Pasoori', 'artist': 'Ali Sethi, Shae Gill', 'year': 2022, 'popularity': 97},
        {'name': 'Kesariya', 'artist': 'Arijit Singh', 'year': 2022, 'popularity': 95},
        {'name': 'Samjhawan', 'artist': 'Arijit Singh, Shreya Ghoshal', 'year': 2014, 'popularity': 90},
        {'name': 'Tu Jhoom', 'artist': 'Abida Parveen, Naseebo Lal', 'year': 2022, 'popularity': 88},
        {'name': 'Iktara', 'artist': 'Amit Trivedi, Kavita Seth', 'year': 2009, 'popularity': 89},
        {'name': 'Phir Se Ud Chala', 'artist': 'Mohit Chauhan', 'year': 2011, 'popularity': 86},
        {'name': 'Nazm Nazm', 'artist': 'Arko', 'year': 2017, 'popularity': 88},
        {'name': 'Sooha Saaha', 'artist': 'Alia Bhatt', 'year': 2014, 'popularity': 84},
        {'name': 'Ilahi', 'artist': 'Arijit Singh', 'year': 2013, 'popularity': 88},
        {'name': 'Qaafirana', 'artist': 'Arijit Singh, Nikhita Gandhi', 'year': 2018, 'popularity': 89},
        {'name': 'Rasiya', 'artist': 'Shreya Ghoshal, Tushar Joshi', 'year': 2022, 'popularity': 92},
        {'name': 'Kun Faya Kun', 'artist': 'A.R. Rahman, Javed Ali', 'year': 2011, 'popularity': 91},
        {'name': 'Heeriye', 'artist': 'Arijit Singh, Jasleen Royal', 'year': 2023, 'popularity': 94},
        {'name': 'Phir Aur Kya Chahiye', 'artist': 'Arijit Singh', 'year': 2023, 'popularity': 93},
        {'name': 'Waqt Ki Baatein', 'artist': 'Dream Note', 'year': 2016, 'popularity': 82},
        {'name': 'Nadaan Parinde', 'artist': 'A.R. Rahman, Mohit Chauhan', 'year': 2011, 'popularity': 87},
        {'name': 'Khaabon Ke Parinday', 'artist': 'Mohit Chauhan, Alyssa Mendonsa', 'year': 2011, 'popularity': 86},
        {'name': 'Tu Aaja', 'artist': 'Shubh', 'year': 2023, 'popularity': 90},
        {'name': 'Daryaa', 'artist': 'Ammy Virk, Shahid Mallya', 'year': 2018, 'popularity': 89},
        {'name': 'Moh Moh Ke Dhaage', 'artist': 'Papon, Monali Thakur', 'year': 2015, 'popularity': 88},
        {'name': 'Ranjha', 'artist': 'B Praak, Jasleen Royal', 'year': 2021, 'popularity': 93},
        {'name': 'Kabhii Tumhhe', 'artist': 'Darshan Raval', 'year': 2021, 'popularity': 87},
        {'name': 'Rait Zara Si', 'artist': 'A.R. Rahman, Shashaa Tirupati', 'year': 2021, 'popularity': 89},
        {'name': 'Baarishein', 'artist': 'Anuv Jain', 'year': 2019, 'popularity': 88},
        {'name': 'Shauq', 'artist': 'Amit Trivedi, Shilpa Rao', 'year': 2022, 'popularity': 87},
        {'name': 'Tere Bina', 'artist': 'A.R. Rahman, Chinmayi', 'year': 2007, 'popularity': 90},
        {'name': 'Bulleya', 'artist': 'Amit Mishra, Shilpa Rao', 'year': 2016, 'popularity': 88},
        {'name': 'Tere Jeya Hor Disda', 'artist': 'Prabh Gill', 'year': 2019, 'popularity': 86},
        {'name': 'Ve Maahi', 'artist': 'Arijit Singh, Asees Kaur', 'year': 2019, 'popularity': 92},
        {'name': 'Kabira (Encore)', 'artist': 'Harshdeep Kaur, Arijit Singh', 'year': 2013, 'popularity': 89},
        {'name': 'Tum Ho', 'artist': 'Mohit Chauhan', 'year': 2011, 'popularity': 85},
        {'name': 'Afreen Afreen', 'artist': 'Rahat Fateh Ali Khan, Momina Mustehsan', 'year': 2016, 'popularity': 91},
        {'name': 'Tujhe Sochta Hoon', 'artist': 'KK', 'year': 2012, 'popularity': 87},
        {'name': 'Jaan Nisaar', 'artist': 'Arijit Singh', 'year': 2018, 'popularity': 86},
        {'name': 'Dilbaro', 'artist': 'Harshdeep Kaur, Vibha Saraf', 'year': 2018, 'popularity': 87},
        {'name': 'Kho Gaye Hum Kahan', 'artist': 'Jasleen Royal, Prateek Kuhad', 'year': 2016, 'popularity': 85},
        {'name': 'Maahi Ve', 'artist': 'A.R. Rahman, Sadhana Sargam', 'year': 2010, 'popularity': 87},
        {'name': 'Zara Zara', 'artist': 'Bombay Jayashri', 'year': 2001, 'popularity': 88},
        {'name': 'Jogi', 'artist': 'Yasser Desai, Aakanksha Sharma', 'year': 2017, 'popularity': 85},
        {'name': 'Aahista', 'artist': 'Arijit Singh', 'year': 2017, 'popularity': 84},
        {'name': 'Sawan Aaya Hai', 'artist': 'Arijit Singh', 'year': 2014, 'popularity': 86},
        {'name': 'Main Tenu Samjhawan Ki', 'artist': 'Arijit Singh', 'year': 2014, 'popularity': 87},
        {'name': 'Tu Hi Haqeeqat', 'artist': 'Javed Ali', 'year': 2009, 'popularity': 85},
        {'name': 'Cold/Mess', 'artist': 'Prateek Kuhad', 'year': 2018, 'popularity': 88},
        {'name': 'Enna Sona', 'artist': 'Arijit Singh', 'year': 2017, 'popularity': 89},
        {'name': 'Bol Do Na Zara', 'artist': 'Armaan Malik', 'year': 2016, 'popularity': 87},
        {'name': 'Saiyaara', 'artist': 'Mohit Chauhan', 'year': 2012, 'popularity': 88},
        {'name': 'Tere Sang Yaara', 'artist': 'Atif Aslam', 'year': 2016, 'popularity': 90},
        {'name': 'Zaroori Tha', 'artist': 'Rahat Fateh Ali Khan', 'year': 2014, 'popularity': 89}
    ],
    'Energetic': [
        {'name': 'Naatu Naatu', 'artist': 'Rahul Sipligunj, Kaala Bhairava', 'year': 2022, 'popularity': 97},
        {'name': 'Kaavaalaa', 'artist': 'Anirudh Ravichander, Shilpa Rao', 'year': 2023, 'popularity': 96},
        {'name': 'Halamithi Habibo', 'artist': 'Anirudh Ravichander', 'year': 2022, 'popularity': 93},
        {'name': 'Oo Antava', 'artist': 'Indravathi Chauhan', 'year': 2021, 'popularity': 95},
        {'name': 'Arabic Kuthu', 'artist': 'Anirudh Ravichander, Jonita Gandhi', 'year': 2022, 'popularity': 94},
        {'name': 'Pushpa - The Rise (Title Track)', 'artist': 'Devi Sri Prasad', 'year': 2021, 'popularity': 92},
        {'name': 'Butta Bomma', 'artist': 'Armaan Malik', 'year': 2020, 'popularity': 91},
        {'name': 'Srivalli', 'artist': 'Sid Sriram', 'year': 2021, 'popularity': 93},
        {'name': 'Saami Saami', 'artist': 'Mounika Yadav', 'year': 2021, 'popularity': 92},
        {'name': 'Vaathi Coming', 'artist': 'Anirudh Ravichander, Gana Balachandar', 'year': 2021, 'popularity': 95},
        {'name': 'Naacho Naacho', 'artist': 'Vishal Mishra, Rahul Sipligunj', 'year': 2021, 'popularity': 96},
        {'name': 'Current Laga Re', 'artist': 'Nakash Aziz, Dhvani Bhanushali', 'year': 2022, 'popularity': 91},
        {'name': 'Jhoome Jo Pathaan', 'artist': 'Arijit Singh, Sukriti Kakar', 'year': 2023, 'popularity': 94},
        {'name': 'O Saki Saki', 'artist': 'Neha Kakkar, Tulsi Kumar', 'year': 2019, 'popularity': 90},
        {'name': 'Muqabla', 'artist': 'Yash Narvekar, Parampara Thakur', 'year': 2020, 'popularity': 89},
        {'name': 'Amplifier', 'artist': 'Imran Khan', 'year': 2009, 'popularity': 88},
        {'name': 'Kala Chashma', 'artist': 'Badshah, Neha Kakkar', 'year': 2016, 'popularity': 93},
        {'name': 'Aaj Ki Raat', 'artist': 'Madhushree, Alisha Chinai', 'year': 2006, 'popularity': 87},
        {'name': 'Aankh Marey', 'artist': 'Neha Kakkar, Mika Singh', 'year': 2018, 'popularity': 90},
        {'name': 'Garmi', 'artist': 'Badshah, Neha Kakkar', 'year': 2020, 'popularity': 88},
        {'name': 'Genda Phool', 'artist': 'Badshah, Payal Dev', 'year': 2020, 'popularity': 89},
        {'name': 'Proper Patola', 'artist': 'Diljit Dosanjh, Badshah', 'year': 2018, 'popularity': 88},
        {'name': 'G.O.A.T.', 'artist': 'Diljit Dosanjh', 'year': 2020, 'popularity': 90},  # Continued from here
        {'name': 'Brown Munde', 'artist': 'AP Dhillon, Gurinder Gill', 'year': 2020, 'popularity': 92},
        {'name': 'Lamberghini', 'artist': 'The Doorbeen, Ragini', 'year': 2018, 'popularity': 88},
        {'name': 'Satisfya', 'artist': 'Imran Khan', 'year': 2013, 'popularity': 87},
        {'name': 'Tauba Tauba', 'artist': 'Badshah', 'year': 2023, 'popularity': 91},
        {'name': 'Rowdy Baby', 'artist': 'Dhanush, Dhee', 'year': 2018, 'popularity': 93},
        {'name': 'Enjoy Enjaami', 'artist': 'Dhee, Arivu', 'year': 2021, 'popularity': 90},
        {'name': 'Mercy', 'artist': 'Badshah', 'year': 2017, 'popularity': 86},
        {'name': 'Buzz', 'artist': 'Aastha Gill, Badshah', 'year': 2018, 'popularity': 85},
        {'name': 'Sip Sip', 'artist': 'Jasmine Sandlas', 'year': 2018, 'popularity': 84},
        {'name': 'Malang', 'artist': 'Ved Sharma', 'year': 2020, 'popularity': 89},
        {'name': 'Selfie Le Le Re', 'artist': 'Vishal Dadlani', 'year': 2015, 'popularity': 87},
        {'name': 'Lungi Dance', 'artist': 'Yo Yo Honey Singh', 'year': 2013, 'popularity': 88},
        {'name': 'Badri Ki Dulhania', 'artist': 'Dev Negi, Neha Kakkar', 'year': 2017, 'popularity': 89},
        {'name': 'Psycho Saiyaan', 'artist': 'Sachet Tandon', 'year': 2019, 'popularity': 86},
        {'name': 'Jai Jai Shivshankar', 'artist': 'Vishal Dadlani, Benny Dayal', 'year': 2019, 'popularity': 90},
        {'name': 'Nagada Sang Dhol', 'artist': 'Shreya Ghoshal', 'year': 2013, 'popularity': 88},
        {'name': 'Wakhra Swag', 'artist': 'Navv Inder, Badshah', 'year': 2015, 'popularity': 87},
        {'name': 'Koka', 'artist': 'Badshah', 'year': 2019, 'popularity': 85},
        {'name': 'Illegal Weapon 2.0', 'artist': 'Jasmine Sandlas, Garry Sandhu', 'year': 2020, 'popularity': 88},
        {'name': 'Laung Laachi', 'artist': 'Mannat Noor', 'year': 2018, 'popularity': 89},
        {'name': 'Sakhiyaan', 'artist': 'Maninder Buttar', 'year': 2018, 'popularity': 87},
        {'name': 'Chikni Chameli', 'artist': 'Shreya Ghoshal', 'year': 2011, 'popularity': 90},
        {'name': 'Party All Night', 'artist': 'Yo Yo Honey Singh', 'year': 2013, 'popularity': 86},
        {'name': 'Mauja Hi Mauja', 'artist': 'Mika Singh', 'year': 2007, 'popularity': 88},
        {'name': 'Paagal', 'artist': 'Badshah', 'year': 2019, 'popularity': 89},
        {'name': 'Makhna', 'artist': 'Yo Yo Honey Singh', 'year': 2018, 'popularity': 87},
        {'name': 'Kalaastar', 'artist': 'Yo Yo Honey Singh', 'year': 2023, 'popularity': 90}
    ]
}

# Create DataFrame
data = []
for mood, songs in songs_by_mood.items():
    for song in songs:
        song['mood'] = mood
        data.append(song)

music_df = pd.DataFrame(data)

# Save to CSV
music_df.to_csv('data_moods.csv', index=False)

print(f"Dataset created with {len(music_df)} songs.")
print(f"Mood distribution:")
print(music_df['mood'].value_counts())
print("\nSample of the dataset:")
print(music_df.head())